openapi: 3.0.0
info:
  title: API REST
  version: 0.1
servers:
  - url: http://localhost:3000/
tags:
  - name: funcionarios
paths:
  /funcionarios:
    get:
      summary: Lista todos os funcionarios
      tags:
        - funcionarios
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOffuncionarios'                  
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
    post:
      tags:
        - funcionarios
    put:
      tags:
        - funcionarios
    delete:
      tags:
        - funcionarios
components:
  schemas:
  securitySchemes: