openapi: 3.0.0
info:
  title: API REST
  version: 0.1
servers:
  - url: http://localhost:3000/
tags:
  - name: voluntarios
paths:
  /voluntarios:
    get:
      summary: Lista todos os voluntarios
      tags:
        - voluntarios
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfVoluntarios'                  
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
    post:
      tags:
        - voluntarios
    put:
      tags:
        - voluntarios
    delete:
      tags:
        - voluntarios
components:
  schemas:
  securitySchemes:
